In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    "The movie was fantastic and full of suspense",
    "I did not enjoy the film at all",
    "What a wonderful performance by the lead actor",
    "The plot was weak and the characters were boring",
    "Absolutely loved the cinematography and music",
    "The story was predictable and unoriginal",
    "Great acting but the pacing was too slow",
    "A masterpiece with emotional depth and strong storytelling",
    "Terrible movie — waste of time",
    "The film had stunning visuals but lacked substance"
]

In [16]:
# Define Vocabulary size

vocab_size=1000

In [17]:
# One Hot Representation

one_hot_repr= [one_hot(words, vocab_size)for words in sent]
one_hot_repr

[[548, 547, 932, 335, 396, 84, 288, 997],
 [951, 493, 460, 54, 548, 865, 681, 562],
 [471, 2, 158, 729, 204, 548, 43, 862],
 [548, 931, 932, 556, 396, 548, 803, 125, 728],
 [827, 119, 548, 568, 396, 106],
 [548, 901, 932, 597, 396, 175],
 [364, 283, 493, 548, 326, 932, 648, 952],
 [2, 371, 39, 69, 670, 396, 13, 588],
 [220, 547, 79, 642, 288, 585],
 [548, 865, 338, 773, 841, 493, 788, 616]]

In [18]:
# Word EMbedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [19]:
sent_length=10
embedded_docs= pad_sequences(one_hot_repr, padding='pre', maxlen= sent_length)
embedded_docs

array([[  0,   0, 548, 547, 932, 335, 396,  84, 288, 997],
       [  0,   0, 951, 493, 460,  54, 548, 865, 681, 562],
       [  0,   0, 471,   2, 158, 729, 204, 548,  43, 862],
       [  0, 548, 931, 932, 556, 396, 548, 803, 125, 728],
       [  0,   0,   0,   0, 827, 119, 548, 568, 396, 106],
       [  0,   0,   0,   0, 548, 901, 932, 597, 396, 175],
       [  0,   0, 364, 283, 493, 548, 326, 932, 648, 952],
       [  0,   0,   2, 371,  39,  69, 670, 396,  13, 588],
       [  0,   0,   0,   0, 220, 547,  79, 642, 288, 585],
       [  0,   0, 548, 865, 338, 773, 841, 493, 788, 616]])

In [20]:
# Feature Representation

dim=15

In [21]:
model= Sequential()
model.add(Embedding(vocab_size, dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 15)            15000     
                                                                 
Total params: 15,000
Trainable params: 15,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.predict(embedded_docs)
# each word is represented by 15 dimensions

1/1 [==============================] - 0s 24ms/step


array([[[ 0.00180923,  0.01088388, -0.03170055, ..., -0.04144708,
         -0.01527166,  0.01583269],
        [ 0.00180923,  0.01088388, -0.03170055, ..., -0.04144708,
         -0.01527166,  0.01583269],
        [-0.0013308 ,  0.03442788,  0.01401922, ...,  0.03523321,
          0.02418159,  0.02361215],
        ...,
        [-0.04329005,  0.0356842 ,  0.02719316, ...,  0.01747271,
         -0.02454876, -0.01730405],
        [ 0.01852647,  0.00813252, -0.04378239, ..., -0.04780173,
         -0.01911378,  0.0111203 ],
        [-0.00246144, -0.04649894, -0.04138749, ..., -0.02705718,
         -0.03100135, -0.0032855 ]],

       [[ 0.00180923,  0.01088388, -0.03170055, ..., -0.04144708,
         -0.01527166,  0.01583269],
        [ 0.00180923,  0.01088388, -0.03170055, ..., -0.04144708,
         -0.01527166,  0.01583269],
        [ 0.03503262, -0.03831851, -0.04140913, ...,  0.02628651,
          0.03424199, -0.0281071 ],
        ...,
        [ 0.01102244, -0.03947977,  0.0042134 , ...,  

In [ ]:
model.predict(embedded_docs[0]) 

1/1 [==============================] - 0s 37ms/step


array([[ 1.8092282e-03,  1.0883879e-02, -3.1700552e-02,  1.4839020e-02,
         5.9033036e-03,  3.4777410e-03, -1.5113484e-02,  2.4124075e-02,
         3.8306620e-02, -2.8172089e-02, -4.4575285e-02, -2.6390577e-02,
        -4.1447081e-02, -1.5271664e-02,  1.5832689e-02],
       [ 1.8092282e-03,  1.0883879e-02, -3.1700552e-02,  1.4839020e-02,
         5.9033036e-03,  3.4777410e-03, -1.5113484e-02,  2.4124075e-02,
         3.8306620e-02, -2.8172089e-02, -4.4575285e-02, -2.6390577e-02,
        -4.1447081e-02, -1.5271664e-02,  1.5832689e-02],
       [-1.3308041e-03,  3.4427885e-02,  1.4019225e-02, -1.6022697e-03,
        -4.6475302e-02, -1.6506471e-02, -2.1959042e-02, -3.6095940e-02,
        -2.7422106e-02,  3.1347599e-02,  4.6386924e-02, -8.3912238e-03,
         3.5233211e-02,  2.4181593e-02,  2.3612153e-02],
       [-7.6148137e-03, -1.1448633e-02,  2.8389279e-02, -1.6802251e-02,
        -1.6794730e-02, -1.6993962e-02, -2.0577908e-03, -2.4043465e-02,
        -4.5397449e-02,  2.8101448e-0